# [ FEATURE SETTINGS ]
# The list of features involves HexRPG split up into chunks of different features of the plugin
# If you do not like specific features, you can disable them in this list
feature-settings:
  item-stats: true
  scrolls: true
  effect-sockets: true
  player-shops: true
  loot-drops: true
  backpacks: true
  drop-tables: true
  player-menu:
    trading: true
    stealing: true

# [LANGUAGE SETTINGS]
language-settings:
  default: 'english.yml'

# [STEALING]
# The 'stealing-time' value is given in ticks. 20 ticks = 1 second
stealing:
  stealing-time: 100
  success-rate: 5

# [WORLD SETTINGS]
world-settings:
  disable-storm: false
  remove-farmland-on-step: true
  burn-hostiles: true

# [DEATH SETTINGS]
# Clearing the drops only deletes the vanilla drops and NOT the drop table rolled items
death-settings:
  disable-death-message: false
  clear-player-drops: false
  clear-other-drops: false

# [PLAYER SHOP SETTINGS]
player-shop-settings:
  upgrade-slots-cost: 400
  max-rows: 4

# [ STATS SETTINGS ]
stats-settings:
  # Enabling forced stats will result in ALL items to be given stats or be set to unidentified items if the item meets the material given in the rpgitem.yml file
  # Forced stats only works if there are no duplicate item material types are setup in the rpgitem.yml file
  forced-stats:
    enabled: false
    identify-rate: 50.0