# Format for items: {drop-rate}:{item-name/rpg-item}:{amount/amount-range}
# For the item-name please use the following list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# For the rpg-item you will have to use the key from the RPG items setup in the rpgitem.yml file
#
# If 'override-default' is set to 'true' the default drop table will NOT be rolled whenever the entity dies. If this is set 'false' both drop tables will be rolled
# For the default drop table 'override-default' has no effect
default:
  override-default: true
  rolls: 1
  drops:
    - '0.5:sinister-blade:1'
    - '0.05:xaisians-sword:1'
    - '0.2:xaisians-combat-scroll:1'
zombie:
  override-default: false
  rolls: 1
  drops:
    - '10:scroll-of-power:1'
    - '10:scroll-of-courage:1'
    - '5:xaisians-combat-scroll:1'
    - '4:xaisians-scroll:1'
    - '10:iron_ingot:3-6'
    - '4:sinister-blade:1'
    - '35:cake:1'
    - '10:cake:2'
    - '10:birch_log:4'
    - '10:dark_oak_log:4'
skeleton:
  override-default: false
  rolls: 2
  drops:
    - '20:bread:1-2'
    - '10:cake:1'
    - '20:apple:1-3'
    - '2:cobblestone:32-64'
    - '2:stone:32-64'
    - '1:sinister-blade:1'
    - '0.8:helm-of-nozit:1'
    - '0.7:helios-platebody:1'
    - '0.3:xaisians-sword:1'
creeper:
  override-default: false
  rolls: 2
  drops:
    - '50:gunpowder:2-6'
    - '10:gunpowder:6-12'
    - '2:tnt:1-2'
sheep:
  override-default: true
  rolls: 3
  drops:
    - '20:white_wool:1'
    - '20:orange_wool:1'
    - '20:red_wool:1'
    - '20:green_wool:1'
    - '20:blue_wool:1'
    - '20:light_blue_wool:1'
    - '20:yellow_wool:1'
    - '20:lime_wool:1'
enderman:
  override-default: false
  rolls: 1
  drops:
    - '10:ender-signal:1'
ender_dragon:
  override-default: false
  rolls: 1
  drops:
    - '20:victorious-aura:1'
wither:
  override-default: false
  rolls: 1
  drops:
    - '20:victorious-aura:1'
blaze:
  override-default: false
  rolls: 1
  drops:
    - '2:infernal-projectile-scroll:1'