# Particles format: {particle},{count},{x-offset},{y-offset},{z-offset},{tick-delay}

# For the 'particle' use the following list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# 'tick-delay' is a number that represents the amount of time the plugin will wait before playing the particle.
# 20 ticks = 1s
# 10 ticks = 0.5s
# 5 ticks = 0.25s
# 0 ticks = 0s (no delay)

# Note: Every particle played by an Effect Socket is looped every second. This might become configurable later.

flames:
  appearance:
    display-item:
      name: 'LAPIS_LAZULI'
      data: 0
    display-name: 'Eternal flames'
  particles:
    - 'flame,1,0.0,0.3,0.0,0'
    - 'flame,1,0.0,0.3,0.0,5'
    - 'flame,1,0.0,0.3,0.0,10'
    - 'flame,1,0.0,0.3,0.0,15'
ender-signal:
  appearance:
    display-item:
      name: 'LAPIS_LAZULI'
      data: 0
    display-name: 'Ender signal'
  particles:
    - 'portal,10,0.0,1.4,0.0,0'
    - 'portal,10,0.0,1.4,0.0,5'
    - 'portal,10,0.0,1.4,0.0,10'
    - 'portal,10,0.0,1.4,0.0,15'
victorious-aura:
  appearance:
    display-item:
      name: 'LAPIS_LAZULI'
      data: 0
    display-name: 'Victorious aura'
  particles:
    - 'villager_happy,1,0.0,0.0,-0.2,0'
    - 'villager_happy,1,0.0,0.12,-0.2,1'
    - 'villager_happy,1,0.0,0.24,-0.2,2'
    - 'villager_happy,1,0.0,0.36,-0.2,3'
    - 'villager_happy,1,0.0,0.48,-0.2,4'
    - 'villager_happy,1,0.0,0.6,-0.2,5'
    - 'villager_happy,1,0.0,0.72,-0.2,6'
    - 'villager_happy,1,0.0,0.84,-0.2,7'
    - 'villager_happy,1,0.0,0.96,-0.2,8'
    - 'villager_happy,1,0.0,1.08,-0.2,9'
    - 'villager_happy,1,0.0,1.20,-0.2,10'
    - 'villager_happy,1,0.1,1.25,-0.2,11'
    - 'villager_happy,1,-0.1,1.25,-0.2,11'
    - 'villager_happy,1,0.2,1.30,-0.2,12'
    - 'villager_happy,1,-0.2,1.30,-0.2,12'
    - 'villager_happy,1,0.3,1.34,-0.2,13'
    - 'villager_happy,1,-0.3,1.34,-0.2,13'
    - 'villager_happy,1,0.4,1.37,-0.2,14'
    - 'villager_happy,1,-0.4,1.37,-0.2,14'
    - 'villager_happy,1,0.5,1.39,-0.2,15'
    - 'villager_happy,1,-0.5,1.39,-0.2,15'
    - 'villager_happy,1,0.6,1.4,-0.2,16'
    - 'villager_happy,1,-0.6,1.4,-0.2,16'