# Format for items: {item-name/rpg-item}:{amount/amount-range}
# For the item-name please use the following list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# For the rpg-item you will have to use the key from the RPG items setup in the rpgitem.yml file
announce-drop: true
announce-coordinates: true
rates:
  common: 80.0
  rare: 16.0
  superior: 4.0
identify-rpg-items:
  common: false
  rare: true
  superior: true
loot:
  - 'sinister_blade:1'
  - 'diamond_axe:1'
  - 'iron_sword:1'
  - 'apple:1-3'
  - 'bread:1-2'
  - 'golden_helmet:1'
  - 'stone:32-64'
  - 'oak_log:8-16'
  - 'oak_planks:32-64'
  - 'paper:6-12'
  - 'book:1-3'
  - 'sugar_cane:3-6'
  - 'iron_ingot:1-3'
  - 'coal:3-8'
  - 'diamond:1'