required-exp-per-level:
  1: 0
  2: 150
  3: 500
  4: 2000
  5: 7500
  6: 16000
  7: 38000
  8: 70000
  9: 150000
  10: 320000
exp-rates:
  bat: 2
  blaze: 18
  cat: 1
  cave_spider: 8
  chicken: 2
  cod: 1
  cow: 3
  creeper: 12
  dolphin: 1
  donkey: 1
  elder_guardian: 28
  ender_dragon: 350
  enderman: 22
  endermite: 6
  evoker: 6
  fox: 1
  ghast: 45
  giant: 78
  guardian: 18
  horse: 1
  husk: 8
  illusioner: 8
  iron_golem: 16
  llama: 1
  magma_cube: 16
  mule: 1
  mushroom_cow: 1
  ocelot: 2
  panda: 1
  parrot: 1
  phantom: 12
  pig: 2
  pig_zombie: 14
  pillager: 6
  polar_bear: 12
  pufferfish: 2
  rabbit: 1
  ravager: 6
  salmon: 2
  sheep: 2
  shulker: 6
  silverfish: 4
  skeleton: 14
  skeleton_horse: 8
  slime: 10
  snowman: 4
  spider: 10
  squid: 3
  trader_llama: 1
  tropical_fish: 2
  turtle: 2
  vex: 4
  villager: 1
  vindicator: 4
  wandering_trader: 1
  witch: 20
  wither: 200
  wither_skeleton: 30
  wolf: 5
  zombie: 12
  zombie_horse: 8
  zombie_villager: 12