'tutorial':
  requirements:
    leveling:
      level: 0
      experience: 0
    items: {}
  npc:
    name: 'Earl'
    type: 'villager'
  steps:
    1:
      start-dialogue:
        - "NPC::Hello there!"
        - "NPC::I have never seen you. Do we know eachother?"
        - "PLAYER::I don't think so."
        - "PLAYER::I am new here and would like to help people out in this village. Are you possibly in need of someone to help you?"
        - "NPC::I do, but first you will have to gain my trust."
        - "NPC::To do so, could you bring me 2 bread so I can feed my family?"
    2:
      loop-dialogue:
        - "NPC::Hello. It is you again. Did you get 2 bread I asked you for yet?"
      give:
        npc: 'tutorial'
        items:
          - 'bread:2'
    3:
      start-dialogue:
        - "PLAYER::Here is the bread you asked for."
        - "NPC::Thank you so much! I bet my wife and kids will be happy for days now."
        - "PLAYER::No problem."
        - "PLAYER::..."
        - "NPC::..."
        - "PLAYER::So..."
        - "NPC::Right! You were looking for people to help."
        - "NPC::The chef of the village, Henry, was having trouble running his restaurant."
        - "NPC::You might want to go see if he needs your help."
  rewards:
    experience: 250
    
    