package me.cheesyfreezy.hexrpg.rpg.items;

public enum RPGAttributeType {
	PVE_DAMAGE, PVP_DAMAGE, CRITICAL_RATE, CRITICAL_DAMAGE_MULTIPLIER, ADDITIONAL_HEALTH, AGILITY, ARMOR, DODGE_CHANCE, TENACITY, LIFESTEAL, ARMOR_PENETRATION, TRAVEL_SPEED, FLAMABLE_CHANCE, OVERHAUL, IDENTIFICATION
}